---
- name: configure red hat ceph community repository stable key
  rpm_key:
    key: "{{ lookup('file', role_path+'/files/cephstable.asc') }}"
    state: present

- name: configure red hat ceph stable community repository
  yum_repository:
    name: ceph_stable
    description: Ceph Stable repo
    gpgcheck: yes
    state: present
    gpgkey: "{{ lookup('file', role_path+'/files/cephstable.asc') }}"
    baseurl: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}/{{ ceph_stable_redhat_distro }}/$basearch"
